language: rust

matrix:
  include:
    - env: TARGET_BUILD=thumbv6m-none-eabi
      rust: nightly
    - env: TARGET_BUILD=thumbv7em-none-eabi
      rust: nightly
    - env: TARGET_BUILD=thumbv7em-none-eabihf
      rust: nightly
    - env: TARGET_BUILD=thumbv7m-none-eabi
      rust: nightly
    - env: TARGET_BUILD=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET_BUILD=x86_64-unknown-linux-gnu
      rust: nightly

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

#after_success:
#  - bash ci/after_success.sh

notifications:
  email:
    on_success: never