language: rust

matrix:
  include:
    - env: TARGET_BUILD=thumbv6m-none-eabi
      rust: nightly
    - env: TARGET_BUILD=thumbv7em-none-eabihf
      rust: nightly
    - env: TARGET_BUILD=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET_BUILD=x86_64-unknown-linux-gnu
      rust: nightly

before_install:
  - set -e
  - rustup self update
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi

install:
  - rustup override set nightly
  - rustup component add rust-src
  - rustup target add arm-unknown-linux-gnueabi
  - rustup target add armv7-unknown-linux-gnueabihf
  - source ~/.cargo/env || true
  - mv .cargo ._cargo
  - cargo install xargo || true
  - mv ._cargo .cargo

script:
  - xargo build --target $TARGET_BUILD
  - xargo build --target $TARGET_BUILD --release

after_script: set +e

cache:
  cargo: true
  directories:
    - $HOME/.xargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

#after_success:
#  - bash ci/after_success.sh

notifications:
  email:
    on_success: never