language: rust

matrix:
  include:
    - env: TARGET_BUILD=thumbv6m-none-eabi
    - env: TARGET_BUILD=thumbv7em-none-eabi
    - env: TARGET_BUILD=thumbv7em-none-eabihf
    - env: TARGET_BUILD=thumbv7m-none-eabi
    - env: TARGET_BUILD=arm-unknown-linux-gnueabihf
    - env: TARGET_BUILD=x86_64-unknown-linux-gnu

before_install:
  - set -e
  - rustup self update
  - sudo apt-get update -qq

install:
  - rustup override set nightly
  - rustup component add rust-src
  - rustup target add arm-unknown-linux-gnueabi
  - rustup target add armv7-unknown-linux-gnueabihf
  - source ~/.cargo/env || true

script:
  - cargo build --target $TARGET_BUILD
  - cargo build --target $TARGET_BUILD --release

#after_success:
#  - bash ci/after_success.sh

notifications:
  email:
    on_success: never
