name: build targets
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: rust-lang/simpleinfra/github-actions/simple-ci@master
        with:
          check_fmt: true

      - name: Publish crate
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
        if: startsWith(github.event.ref, 'refs/tags/v')